spring.application.name=UserService 
server.port=8081
#spring.datasource.url=jdbc:postgresql://localhost:5432/User_Service
#spring.datasource.username=postgres
#spring.datasource.password=root
spring.datasource.url=jdbc:postgresql://ep-icy-butterfly-ai9cntcc-pooler.c-4.us-east-1.aws.neon.tech:5432/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_ib3DzvmCEaU0
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.datasource.hikari.maximum-pool-size=5